Adding packer validation command in packer_pull_request.yaml

diff --git a/.github/workflows/packer_pull_request.yaml b/.github/workflows/packer_pull_request.yaml
--- a/.github/workflows/packer_pull_request.yaml
+++ b/.github/workflows/packer_pull_request.yaml
@@ -48,4 +48,17 @@ jobs:
               echo "$output"
               exit 1
             fi
+        - name: Validate packer file
+          run: |
+            pwd
+            ls -la
+            cd webapp
+            ls -la
+            expected_output="The configuration is valid."
+            output=$(packer validate ./aws-debian.pkr.hcl)
+            if ["$output" != expected_output]; then
+              echo "Packer validation failed. Found some errors:"
+              echo "$output"
+              exit 1
+            fi
             
